### PR TITLE
Fix issue #2

### PR DESCRIPTION
**Pull request by sprat**
Fix issue #2

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@sprat Merged! Thanks for this.

**Comment by sprat** [comment]
Thanks for the merge. Can you also make a new release on ansible galaxy so that I can use this fix, please?

**Comment by mrlesmithjr** [comment]
Just implemented Molecule testing and added Travis CI back into this role. It **SHOULD** now be updated in Ansible Galaxy here shortly!

Ref: #5

**Comment by sprat** [comment]
Not tested yet, but many thanks for the release!

**Pull request merged**
